version: '3.4'

services:
  devfreela.api:
    image: ${DOCKER_REGISTRY-}devfreelaapi
    build:
      context: .
      dockerfile: src/DevFreela.API/DevFreela.API/Dockerfile
    depends_on:
      - devfreela.sqlServer
      - devfreela.rabbitmq


  devfreela.sqlServer:
    container_name: devfreela.sqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
        SA_PASSWORD: "DevFreelaDB@123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"



  devfreela.rabbitmq:
    container_name: devfreela.rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  

  

    